/**
 * NOTE: This is a fix for the react-helmet type declarations. When target and module
 *       for typescript compiler is 'es6', the declarations in the DefinitelyTyped
 *       repository isn't working since we need to grab the default import of Helmet:
 *          import Helmet from 'react-helmet';
 *       React will not recognize the element if we instead use something like this:
 *          import * as Helmet from 'react-helmet';
 *       This is because when it compiles, it will turn into an object which inside
 *       has a property 'Helmet' (or 'default', not sure which).
 */
// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/4595e61ad1e8c5f48255a016471487f100a818f8/react-helmet/react-helmet.d.ts
declare namespace ReactHelmet {
    import React = __React;

    interface HelmetProps {
        base?: any;
        defaultTitle?: string;
        htmlAttributes?: any;
        link?: Array<any>;
        meta?: Array<any>;
        script?: Array<any>;
        title?: string;
        titleTemplate?: string;
        onChangeClientState?: (newState: any) => void;
    }

    interface HelmetData {
        base: HelmetDatum;
        htmlAttributes: HelmetDatum;
        link: HelmetDatum;
        meta: HelmetDatum;
        script: HelmetDatum;
        title: HelmetDatum;
    }

    interface HelmetDatum {
        toString(): string;
        toComponent(): React.Component<any, any>;
    }

    class HelmetComponent extends React.Component<HelmetProps, any> {}
}

declare module "react-helmet" {
    var Helmet: {
        (): ReactHelmet.HelmetComponent
        rewind(): ReactHelmet.HelmetData
    }

    export default Helmet;
    // Above used to be 'export = Helmet;'
}
